### ISSUE TITLE
Typo Issues

### ISSUE THREAD

**Issue by JeremyWu917** [whuanle/maomi#1]
See below 🏷️ 
![image](https://github.com/whuanle/maomi/assets/54832272/88d9c38b-4c29-4012-b6df-cafb16a13579)

**Comment by whuanle** [comment]
> See below 🏷️ ![image](https://private-user-images.githubusercontent.com/54832272/316211504-88d9c38b-4c29-4012-b6df-cafb16a13579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTY1NTAsIm5iZiI6MTcxMTQ1NjI1MCwicGF0aCI6Ii81NDgzMjI3Mi8zMTYyMTE1MDQtODhkOWMzOGItNGMyOS00MDEyLWI2ZGYtY2FmYjE2YTEzNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEyMzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYzNhMWUyZjM3NDg3OWFmODdkMmViYWI0NWVhM2ZkNDEyZTNmN2YxNzhiNzkzYjAzNjE0NjYwMmU3NjgwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.radJRjA7ZT4ayKPrL2mvR2B8qddfDb8ZRHXeR6o-PT0)

感恩，您是好人。
